name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours

jobs:
  update:
    runs-on: ubuntu-latest
    concurrency: cd
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Sync
        run: yarn script:sync
        continue-on-error: true
        timeout-minutes: 110

      - name: Create indexes
        run: yarn script:create-indexes
        continue-on-error: true
        timeout-minutes: 110

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data
          git diff-index --quiet HEAD || git commit -m "Updated indexes"
          git status
          git pull --rebase --autostash
          git push